
## ??????
dataSource.user=root
dataSource.password=12345678

## ???????????
dataSource.maxPoolSize=20
dataSource.password=12345678
dataSource.minPoolSize=6
dataSource.initialPoolSize=5

## ????????
#dataSource.driverClass=org.postgresql.Driver
#dataSource.jdbcUrl=jdbc:postgresql://192.168.235.136:26000/hrm_db


## Mysql??????
dataSource.jdbcUrl=jdbc:mysql://127.0.0.1:3306/hrm_db
dataSource.driverClass=com.mysql.cj.jdbc.Driver
